FROM ubuntu:18.04
RUN apt-get -y update
RUN apt-get -y install nodejs
RUN apt-get -y install npm
RUN apt-get -y install git
RUN apt-get -y install rsync
RUN apt-get -y install m4
RUN npm install -g esy@0.1.8
