FROM ubuntu:18.04
RUN apt-get -y update
RUN apt-get -y install nodejs
RUN apt-get -y install npm
RUN apt-get -y install git
RUN apt-get -y install rsync
RUN apt-get -y install m4
RUN apt-get -y install autoconf
RUN apt-get -y install automake
RUN npm install -g esy@0.2.11
